[toc]

## 处理错误

C# 使用 **异常** 抓取错误并使用适当的语句处理异常。

## 尝试执行代码和捕捉异常

```csharp
string str = Console.ReadLine();
try
{
	int num = int.Parse(str);
	Console.WriteLine("Correct");
}
catch(FormatException e)
{
	Console.WriteLine(e);
}
Console.WriteLine("Here");
```

- 当在控制台正确输入一个整数时，控制台显示了 Correct 和 Here。
- 当在控制台输入了一个字符串时，控制台显示了错误信息以及 Here。

### 未处理的异常

当我们把 `try ... catch` 语句块注释掉时：

> 快速注释：Ctrl + k + c，取消注释：Ctrl + k + u

```csharp
string str = Console.ReadLine();
//try
//{
	int num = int.Parse(str);
	Console.WriteLine("Correct");
//}
//catch(FormatException e)
//{
//	Console.WriteLine(e);
//}
Console.WriteLine("Here");
```

- 当我们再次运行时，输入一个数字时程序依然正常显示 Correct + Here。
- 当输入一个字符串时，程序输出了错误提示并崩溃。

当我们换成其他异常的时候：

```csharp
string str = Console.ReadLine();
try
{
		int num = int.Parse(str);
		Console.WriteLine("Correct");
}
catch(OverflowException e)         // 它只能抓到数字过大的异常
{
		Console.WriteLine(e);
}
Console.WriteLine("Here");
```

- 当我们再次运行时，输入一个数字时程序依然正常显示 Correct + Here。
- 当输入一个字符串时，程序仍然输出了错误提示并崩溃。

由内向外遍历了所有调用的方法之后，如果还是找不到匹配的 `catch` 处理程序，整个程序终止，报告发生了 **未处理的异常**。

### 使用多个 catch 处理程序

```csharp
string str = Console.ReadLine();
try
{
		int num = int.Parse(str);
		Console.WriteLine("Correct");
}
catch(FormatException e)         // 当输入的不是数字时
{
		Console.WriteLine(e);
}
catch (OverflowException e)      // 当输入的数字过大时
{
		Console.WriteLine(e);
}
Console.WriteLine("Here");
```

### 捕捉多个异常

异常用 **继承层次结构** 进行组织。

> `Exception` 是所有异常的"老祖宗"。

- `FormatException` 和 `OverflowException` 异常都输入 `SystemException` 家族。
- `SystemException` 和其他许多异常又属于 `Exception` 家族。

所以我们可以用 `Exception` 代替 `FormatException` 和 `OverflowException`。

```csharp
string str = Console.ReadLine();
try
{
	int num = int.Parse(str);
	Console.WriteLine("Correct");
}
catch(Exception e)
{
	Console.WriteLine(e);
}
Console.WriteLine("Here");
```

- 如果真的决定捕捉 `Exception`，可以从 `catch` 处理程序中省略它的名称，因为默认捕捉的就是 `Exception`。
- 但是这会导致这个 `catch` 语句块 **没有了参数**，可能无法利用异常中包含的信息。

```csharp
catch   // 这里省略了 Exception
{
	// ...
}
```

假若我们将 `FormatException` 添加在 `Exception` 之前：

```csharp
string str = Console.ReadLine();
try
{
		int num = int.Parse(str);
		Console.WriteLine("Correct");
}
catch(FormatException e){
		Console.WriteLine("Format");
}
catch(Exception e)
{
		Console.WriteLine("Exception");
}
Console.WriteLine("Here");
```

- 当输入的不是数字时，会显示 Format 和 Here。
- 当输入的数字超出范围时，会显示 Exception 和 Here。

当我们将 `FormatException` 和 `Exception` 调换位置时：

```csharp
string str = Console.ReadLine();
try
{
		int num = int.Parse(str);
		Console.WriteLine("Correct");
}
catch (Exception e)
{
		Console.WriteLine("Exception");
}
catch (FormatException e)        // 报错
{
		Console.WriteLine("Format");
}
Console.WriteLine("Here");
```

因为 `catch` 语句块总是从上至下进行筛选，导致所有的异常都被 `Exception` 捕捉到，`FormatException` 永远不会被执行。

> 在实际情况中，推荐将各个异常分别写出来，因为不同的异常需要不同的处理。

### 异常过滤器

**异常过滤器** 影响异常和 `catch` 处理程序的匹配方式，允许指定 `catch` 处理程序的额外使用条件。

```csharp
string str = Console.ReadLine();
try
{
		int num = int.Parse(str);
		Console.WriteLine("Correct");
}
catch (Exception e) when (e.GetType() != typeof(FormatException))
{
		Console.WriteLine("Exception");
}
catch (FormatException e)
{
		Console.WriteLine("Format");
}
Console.WriteLine("Here");
```

使用 `when` 关键字加布尔表达式即可处理除 `FormatException` 异常之外的所有异常。

### 传播异常

当异常发生时，如果没有捕捉该异常，将会把异常 **返回上一级** 进行处理。

> Main 方法的上一级是操作系统，当没有捕捉异常时，操作系统只能终止程序进行处理。

```csharp
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            new Example().f(1);
            new Example().f(2);
            new Example().f(3);
        }
    }

    class Example
    {
        public void f(int x)
        {
            try
            {
                if(x == 1)
                {
                    f1();
                }
                else if(x == 2)
                {
                    f2();
                }
                else
                {
                    f3();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

        private void f1()
        {
            throw new FormatException();
        }

        private void f2()
        {
            throw new OverflowException();
        }

        private void f3()
        {
            throw new IndexOutOfRangeException();
        }
    }
}
```

- 这里使用 `throw` 关键字故意抛出一个异常。
	- 注意这里不同于 java，没有 `throws` 关键字。
- `f` 方法分别调用了 `f1` 方法、`f2` 方法、`f3` 方法，并且抛出的异常都被 `f` 方法的 `catch` 语句块捕捉到，则程序正常结束。
- 通过这个方法我们可以同时捕捉一些相同的异常。

## 使用 checked 和 unchecked 整数运算

```csharp
int num = int.MaxValue;
try
{
	checked
	{
		int x = num++;
		Console.WriteLine("永远都执行不到这里");
	}
}
catch(OverflowException e)
{
	Console.WriteLine(e);
}
```

```csharp
int num = int.MaxValue;
try
{
	int x;
	unchecked
	{
		x = num * num;
	}
	Console.WriteLine(x);    // 输出了错误的数字
}
catch(OverflowException e)
{
	Console.WriteLine(e);    // 没有执行
}
```

- `checked` 语句块会检查特定部分的整数是否溢出。
- `unchecked` 语句块会强制不检查整数溢出。

## 编写 checked 表达式

```csharp
checked
{
	int x = int.MaxValue * int.MaxValue;
}

// 等价于

int x = checked(int.MaxValue * int.MaxValue);
```

> 不能使用 `checked` 和 `unchecked` 关键字控制浮点（非整数）运算。

## 使用 finally 块

在一些情况下，即使在异常发生并捕捉到异常，我们也需要进行一些必要的处理。

- `try` 语句块在异常发生时将跳到 `catch` 语句块中。
- `catch` 语句块在没有异常发生时将不会运行。
- 需要一个 `finally` 语句块处理一些必要的语句。

```csharp
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            new Example().f(1);
            new Example().f(2);
        }
    }

    class Example
    {
        public bool f(int x)
        {
            try
            {
                if(x == 1)
                {
                    throw new Exception();
                }
                else
                {
                    return false;
                }
            }
            catch
            {
                return true;
            }
            finally
            {
                Console.WriteLine("总会被执行");
            }
        }
    }
}
```

- 当传递的参数为 1 时，抛出 `Exception`，在返回 `true` 之前执行了 `finally` 语句块。
- 当传递的参数不为 1 时，没有抛出异常，在返回 `false` 之前执行了 `finally` 语句块。

> 即使执行 `return` 语句，`finally` 也总会被执行。
